[pytest]
DJANGO_SETTINGS_MODULE = config.settings
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
markers =
	legacy: tests legacy no ejecutados por defecto
norecursedirs = tests_legacy
