# Generated by Django 6.0.1 on 2026-02-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shadowcalculation',
            name='att_shadow__employe_69f4d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='shadowcalculation',
            name='att_shadow__differe_9da4dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='shadowcalculation',
            name='att_shadow__created_916277_idx',
        ),
        migrations.RemoveIndex(
            model_name='shadowcalculation',
            name='att_shadow__require_e30127_idx',
        ),
        migrations.RemoveIndex(
            model_name='shadowdifferenceanalysis',
            name='att_shadow__primary_c004e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='shadowdifferenceanalysis',
            name='att_shadow__confide_49f6c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='shadowdifferenceanalysis',
            name='att_shadow__require_e81e82_idx',
        ),
        migrations.RemoveIndex(
            model_name='shadowdifferenceanalysis',
            name='att_shadow__created_e1841e_idx',
        ),
        migrations.RemoveIndex(
            model_name='shadowreviewdecision',
            name='att_shadow__status_4dc750_idx',
        ),
        migrations.RemoveIndex(
            model_name='shadowreviewdecision',
            name='att_shadow__reviewe_890611_idx',
        ),
        migrations.RemoveIndex(
            model_name='shadowreviewdecision',
            name='att_shadow__decided_e47531_idx',
        ),
        migrations.RemoveIndex(
            model_name='shadowreviewdecision',
            name='att_shadow__created_3d2ea3_idx',
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='schedule_type',
            field=models.CharField(default='NONE', max_length=20, verbose_name='Tipo de Horario'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='source_logs_count',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Logs Fuente'),
        ),
        migrations.AddConstraint(
            model_name='dailyattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='uix_daily_attendance_employee_date'),
        ),
        migrations.RemoveField(
            model_name='shadowdifferenceanalysis',
            name='shadow_calculation',
        ),
        migrations.RemoveField(
            model_name='shadowreviewdecision',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='shadowreviewdecision',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='shadowreviewdecision',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='ShadowCalculation',
        ),
        migrations.DeleteModel(
            name='ShadowDifferenceAnalysis',
        ),
        migrations.DeleteModel(
            name='ShadowReviewDecision',
        ),
    ]
