# Generated by Django 6.0.1 on 2026-01-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_authuser'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='biometrictemplate',
            constraint=models.UniqueConstraint(fields=('user', 'type', 'index'), name='uix_bio_template'),
        ),
    ]
