# Generated by Django 6.0.1 on 2026-02-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_biometrictemplate_uix_bio_template'),
        ('core', '0099_forensic_triggers'),
    ]

    operations = [
    ]
