# Generated by Django 6.0.1 on 2026-02-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_merge_20260202_1337'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyattendance',
            name='uix_daily_att',
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='break_minutes',
            field=models.IntegerField(default=0, verbose_name='Minutos de Descanso'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='net_worked_minutes',
            field=models.IntegerField(default=0, verbose_name='Minutos Netos Trabajados'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='night_minutes',
            field=models.IntegerField(default=0, verbose_name='Minutos Nocturnos'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='regular_minutes',
            field=models.IntegerField(default=0, verbose_name='Minutos Regulares'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Late', 'Tardío'), ('Early', 'Salida anticipada'), ('Absent', 'Ausente'), ('Leave', 'Licencia'), ('Worked', 'Trabajado'), ('Incomplete', 'Incompleto'), ('Excessive', 'Excesivo'), ('HolidayWorked', 'Trabajo en Feriado'), ('RestDay', 'Día de Descanso')], default='Absent', max_length=50, verbose_name='Estado'),
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='source_logs_count',
        ),
    ]
