# Generated by Django 6.0.1 on 2026-02-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_remove_dailyattendance_uix_daily_att_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Edicion'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='edited_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Editado Por'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='edited_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo Edicion'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Editado Manual'),
        ),
    ]
