# Generated by Django 6.0.1 on 2026-02-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_attendancelog_edited_at_attendancelog_edited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='cycle_days',
            field=models.IntegerField(
                default=0,
                help_text='Days in rotation cycle (0=weekly, >0=long cycle). Used by shift_v2 engine for long rotations.'
            ),
        ),
    ]
