# Generated by Django 6.0.1 on 2026-02-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_shift_cycle_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='overtime_threshold_minutes',
            field=models.IntegerField(default=0, help_text='Minutos mínimos de overtime para que cuente como hora extra. Ej: 30 = solo cuenta si trabajó al menos 30 min extra', verbose_name='Umbral Mínimo Hora Extra (min)'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='cycle_days',
            field=models.IntegerField(default=0, help_text='0=ciclo semanal (Monday-Sunday), >0=ciclo largo (rotaciones de N días)', verbose_name='Días del ciclo'),
        ),
    ]
