# Generated by Django 6.0.1 on 2026-02-09 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_timetable_time_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('v1_worked_minutes', models.IntegerField(verbose_name='V1 Minutos Trabajados')),
                ('v1_overtime_minutes', models.IntegerField(default=0, verbose_name='V1 Minutos Extra')),
                ('v1_status', models.CharField(max_length=50, verbose_name='V1 Estado')),
                ('v2_worked_minutes', models.IntegerField(verbose_name='V2 Minutos Brutos')),
                ('v2_net_minutes', models.IntegerField(verbose_name='V2 Minutos Netos')),
                ('v2_regular_minutes', models.IntegerField(verbose_name='V2 Minutos Regulares')),
                ('v2_overtime_minutes', models.IntegerField(verbose_name='V2 Minutos Extra')),
                ('v2_night_minutes', models.IntegerField(default=0, verbose_name='V2 Minutos Nocturnos')),
                ('v2_status', models.CharField(max_length=50, verbose_name='V2 Estado')),
                ('difference_minutes', models.IntegerField(help_text='V2 net - V1 worked', verbose_name='Diferencia (minutos)')),
                ('difference_type', models.CharField(choices=[('NONE', 'Sin diferencia'), ('MINOR', 'Diferencia menor'), ('MAJOR', 'Diferencia mayor'), ('CRITICAL', 'Diferencia crítica')], db_index=True, default='NONE', max_length=20, verbose_name='Tipo de Diferencia')),
                ('requires_review', models.BooleanField(db_index=True, default=False, verbose_name='Requiere Revisión')),
                ('fingerprint_v2', models.CharField(blank=True, max_length=64, null=True, verbose_name='Fingerprint V2')),
                ('engine_version', models.CharField(default='2.0.0', max_length=50, verbose_name='Versión Motor V2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('v1_daily_attendance_id', models.IntegerField(blank=True, help_text='Reference to the V1 record being compared', null=True, verbose_name='ID DailyAttendance V1')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_calculations', to='core.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Cálculo Shadow',
                'verbose_name_plural': 'Cálculos Shadow',
                'db_table': 'att_shadow_calculation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShadowDifferenceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_reason', models.CharField(choices=[('BREAK_POLICY', 'Cambio en política de descansos'), ('OVERTIME_POLICY', 'Cambio en política de horas extra'), ('FLEXIBLE_SPLIT', 'Tratamiento de jornada fragmentada'), ('NIGHT_CLASS', 'Cambio en clasificación nocturna'), ('HOLIDAY_DETECT', 'Detección de trabajo en feriado'), ('ORPHAN_PUNCH', 'Manejo de fichadas huérfanas'), ('ROUNDING', 'Diferencia por regla de redondeo'), ('STATUS_CHANGE', 'Cambio en resolución de estado'), ('BUG_V1', 'Posible error en motor V1'), ('UNKNOWN', 'Causa no determinada')], help_text='Razón principal de la diferencia', max_length=30, verbose_name='Causa Principal')),
                ('secondary_reason', models.CharField(blank=True, choices=[('BREAK_POLICY', 'Cambio en política de descansos'), ('OVERTIME_POLICY', 'Cambio en política de horas extra'), ('FLEXIBLE_SPLIT', 'Tratamiento de jornada fragmentada'), ('NIGHT_CLASS', 'Cambio en clasificación nocturna'), ('HOLIDAY_DETECT', 'Detección de trabajo en feriado'), ('ORPHAN_PUNCH', 'Manejo de fichadas huérfanas'), ('ROUNDING', 'Diferencia por regla de redondeo'), ('STATUS_CHANGE', 'Cambio en resolución de estado'), ('BUG_V1', 'Posible error en motor V1'), ('UNKNOWN', 'Causa no determinada')], help_text='Razón adicional que contribuye a la diferencia', max_length=30, null=True, verbose_name='Causa Secundaria')),
                ('confidence_level', models.CharField(choices=[('HIGH', 'Alta confianza'), ('MEDIUM', 'Confianza media'), ('LOW', 'Baja confianza')], default='MEDIUM', max_length=10, verbose_name='Nivel de Confianza')),
                ('explanation', models.TextField(help_text='Texto legible por RRHH explicando la diferencia', verbose_name='Explicación')),
                ('requires_human_review', models.BooleanField(db_index=True, default=False, verbose_name='Requiere Revisión Humana')),
                ('affected_fields', models.JSONField(blank=True, default=dict, help_text='Qué campos específicos difieren (break, overtime, etc.)', verbose_name='Campos Afectados')),
                ('rule_trace', models.JSONField(blank=True, default=list, help_text='Reglas evaluadas y sus resultados', verbose_name='Traza de Reglas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Análisis')),
                ('engine_version', models.CharField(default='1.0.0', max_length=20, verbose_name='Versión del Analizador')),
                ('shadow_calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.shadowcalculation', verbose_name='Cálculo Shadow')),
            ],
            options={
                'verbose_name': 'Análisis de Diferencia Shadow',
                'verbose_name_plural': 'Análisis de Diferencias Shadow',
                'db_table': 'att_shadow_difference_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShadowReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de revisión'), ('IN_PROGRESS', 'En revisión'), ('ACCEPTED', 'Aceptado'), ('ADJUSTED', 'Requiere ajuste de política'), ('ESCALATED', 'Escalado a Legal'), ('CLOSED', 'Cerrado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio de Revisión')),
                ('decision', models.CharField(blank=True, choices=[('V2_CORRECT', 'V2 es correcto'), ('V1_CORRECT', 'V1 es correcto'), ('POLICY_CHANGE', 'Requiere cambio de política'), ('INCONCLUSIVE', 'Resultado inconcluso'), ('N/A', 'No aplica')], max_length=20, null=True, verbose_name='Decisión')),
                ('decision_notes', models.TextField(blank=True, help_text='Justificación obligatoria de la decisión', null=True, verbose_name='Notas de Decisión')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Decisión')),
                ('confidence_override', models.CharField(blank=True, choices=[('HIGH', 'Alta confianza'), ('MEDIUM', 'Confianza media'), ('LOW', 'Baja confianza')], help_text='Si el revisor considera que la confianza debe ser diferente', max_length=10, null=True, verbose_name='Override de Confianza')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_decision', to='core.shadowdifferenceanalysis', verbose_name='Análisis')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shadow_reviews_closed', to='core.user', verbose_name='Cerrado por')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shadow_reviews', to='core.user', verbose_name='Revisor Asignado')),
            ],
            options={
                'verbose_name': 'Decisión de Revisión Shadow',
                'verbose_name_plural': 'Decisiones de Revisión Shadow',
                'db_table': 'att_shadow_review_decision',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shadowcalculation',
            index=models.Index(fields=['employee', 'date'], name='att_shadow__employe_69f4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowcalculation',
            index=models.Index(fields=['difference_type'], name='att_shadow__differe_9da4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowcalculation',
            index=models.Index(fields=['created_at'], name='att_shadow__created_916277_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowcalculation',
            index=models.Index(fields=['requires_review'], name='att_shadow__require_e30127_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowdifferenceanalysis',
            index=models.Index(fields=['primary_reason'], name='att_shadow__primary_c004e8_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowdifferenceanalysis',
            index=models.Index(fields=['confidence_level'], name='att_shadow__confide_49f6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowdifferenceanalysis',
            index=models.Index(fields=['requires_human_review'], name='att_shadow__require_e81e82_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowdifferenceanalysis',
            index=models.Index(fields=['created_at'], name='att_shadow__created_e1841e_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowreviewdecision',
            index=models.Index(fields=['status'], name='att_shadow__status_4dc750_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowreviewdecision',
            index=models.Index(fields=['reviewer'], name='att_shadow__reviewe_890611_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowreviewdecision',
            index=models.Index(fields=['decided_at'], name='att_shadow__decided_e47531_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowreviewdecision',
            index=models.Index(fields=['created_at'], name='att_shadow__created_3d2ea3_idx'),
        ),
    ]
