# Generated by Django 6.0.1 on 2026-02-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_create_shadow_calculation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='off_duty_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Salida'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='on_duty_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Entrada'),
        ),
    ]
